/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Camille Leclercq (https://sketchfab.com/CamilleLeclercq)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dae-villages-egyptian-pottery-4e3d91d47d9e4833881604d35d6b4689
Title: DAE Villages - Egyptian Pottery
*/


import React, { useRef, useEffect } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { a } from '@react-spring/three'
import * as THREE from 'three'
import islandScene from '../assets/3d/island.glb'



const Island = ({ isRotating, setIsRotating, ...props }) => {
    const islandRef = useRef();
    const { nodes, materials, scene } = useGLTF(islandScene)
    // console.log("Model Nodes:", nodes);

    const { gl, viewport } = useThree();
    const lastX = useRef(0)
    const rotationSpeed = useRef(0);
    const dampingFactor = 0.95;


    // Event handler for mouse movement

    const handlePointerDown = (e) => {
        e.stopPropagation();
        setIsRotating(true);
        const clientX = e.touches ? e.touches[0].clientX : e.clientX;
        lastX.current = clientX;
    }

    const handlePointerUp = (e) => {
        e.stopPropagation();
        setIsRotating(false);
    }

    const handlePointerMove = (e) => {
        e.stopPropagation();
        e.preventDefault();

        if (isRotating) {
            const clientX = e.touches ? e.touches[0].clientX : e.clientX;
            const delta = (clientX - lastX.current) / viewport.width;
            islandRef.current.rotation.y += delta * 0.01 * Math.PI;
            lastX.current = clientX;
            rotationSpeed.current = delta * 0.01 * Math.PI;
        }
    }
    useEffect(() => {
        if (islandRef.current) {
            islandRef.current.rotation.set(0, 4.7, 0); // reset to default
        }
    }, []);

    useFrame(() => {
        if (!isRotating) {
            rotationSpeed.current *= dampingFactor;
            islandRef.current.rotation.y += rotationSpeed.current;
        }
    });


    useEffect(() => {
        const canvas = gl.domElement;
        canvas.addEventListener('pointerdown', handlePointerDown);
        canvas.addEventListener('pointerup', handlePointerUp);
        canvas.addEventListener('pointermove', handlePointerMove);
        return () => {
            canvas.removeEventListener('pointerdown', handlePointerDown);
            canvas.removeEventListener('pointerup', handlePointerUp);
            canvas.removeEventListener('pointermove', handlePointerMove);
        }
    }, [gl, handlePointerDown, handlePointerUp, handlePointerMove]);

    return (
        <a.group ref={islandRef} {...props}>
            <mesh
                geometry={nodes.Groundplane_ExtraTexture_0.geometry}
                material={materials.ExtraTexture}
                position={[46.709, 9.028, 33.657]}
            />
            <mesh
                geometry={nodes.Stairs_MainTexture_0.geometry}
                material={materials.MainTexture}
            />
            <mesh
                geometry={nodes.Rocks_MainTexture_0.geometry}
                material={materials.MainTexture}
                position={[0, -2.142, 0]}
            />
            <mesh
                geometry={nodes.Oven_MainTexture_0.geometry}
                material={materials.MainTexture}
            />
            <mesh
                geometry={nodes.WingedSun_MainTexture_0.geometry}
                material={materials.MainTexture}
                position={[-189.694, 167.531, 24.655]}
                rotation={[1.389, 0, 0]}
                scale={0.329}
            />
            <mesh
                geometry={nodes.Ptah_MainTexture_0.geometry}
                material={materials.MainTexture}
                position={[-156.068, 31.22, -28.954]}
                scale={0.565}
            />
            <mesh
                geometry={nodes.House_MainTexture_0.geometry}
                material={materials.MainTexture}
            />
            <mesh
                geometry={nodes.Cats_ExtraTexture_0.geometry}
                material={materials.ExtraTexture}
            />
            <mesh
                geometry={nodes.Plants_ExtraTexture_0.geometry}
                material={materials.ExtraTexture}
            />
            <mesh
                geometry={nodes.CanopicPots_MainTexture_0.geometry}
                material={materials.MainTexture}
            />
            <mesh
                geometry={nodes.Carpets_MainTexture_0.geometry}
                material={materials.MainTexture}
            />
            <mesh
                geometry={nodes.Ladder_MainTexture_0.geometry}
                material={materials.MainTexture}
            />
            <mesh
                geometry={nodes.Jars_MainTexture_0.geometry}
                material={materials.MainTexture}
            />
            <mesh
                geometry={nodes.Extras_MainTexture_0.geometry}
                material={materials.MainTexture}
            />
            <mesh
                geometry={nodes.Racks_MainTexture_0.geometry}
                material={materials.MainTexture}
            />
            <mesh
                geometry={nodes.Props_MainTexture_0.geometry}
                material={materials.MainTexture}
            />
        </a.group>
    )

}

useGLTF.preload(islandScene)


export default Island